version: "2"

services:
    nginx:
      build:
        context: ./docker/nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      container_name: ${NGINX_CONTAINER_NAME}
      working_dir: ${APP_CODE_PATH_CONTAINER}
      ports:
       - "${NGINX_HOST_HTTP_PORT}:80"
       - "${NGINX_HOST_HTTPS_PORT}:443"
      volumes:
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      depends_on:
        - php-fpm    
    php-fpm:
      build: docker/php-fpm
      container_name: ${PHP_FPM_CONTAINER_NAME}   
      working_dir: ${APP_CODE_PATH_CONTAINER}
      volumes:
        - ./docker/php-fpm/php${PHP_VERSION}.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - "9000"      
networks:
  default:
    external:
      name: ${NETWORK_CONTAINERS}   


